version: '3.8'

services:

  desis-db:
    container_name: desis_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: desisdb
      POSTGRES_PASSWORD: 123456
    
